---
jobs:
  - name: Hello World
    plan:
      - task: you-are-welcome
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: ubuntu }
          run:
            path: echo
            args:
              - "\n"
              - "\n"
              - "\n"
              - " ===================\n"
              - " Welcome to my world\n"
              - " ===================\n"
