---
resources:
  - name: concourse-workshop
    type: git
    source:
      uri: https://((github_token))@github.com/((github_user))/concourse-workshop.git
      branch: ((github_branch))

jobs:
  - name: Linting
    plan:
      - get: concourse-workshop
        trigger: true

      - task: linting
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ubuntu
          run:
            path: ./demo/scripts/linting.sh
            dir: concourse-workshop
          inputs:
            - name: concourse-workshop

  - name: Code Style
    plan:
      - get: concourse-workshop
        trigger: true

      - task: check-code-style
        file: ./demo/tasks/code-style.yml

  - name: Tests
    plan:
      - get: concourse-workshop
        trigger: true
        passed: ["Linting", "Code Style"]

      - task: get-depedencies
        file: concourse-workshop/demo/3.Pipeline/tasks/deps.yml

      - in_parallel:
        - task: unit-tests
          file: concourse-workshop/demo/3.Pipeline/tasks/unit-tests.yml

        - task: integration-tests
          file: concourse-workshop/demo/3.Pipeline/tasks/integration-tests.yml
